appId: ${APP_ID}
tags:
  - prod
---
- launchApp
- runFlow:
- runFlow:
    when:
      visible:
        id: "${APP_ID}:id/loginUsernameField"
    file: "subflows/Login.yaml"
- runFlow: "subflows/SearchPatient.yaml"