name: Maestro test on emulator

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - uses: dniHze/maestro-test-action@v1
        with:
          env: |
            MAESTRO_TEST_USERNAME=${{ secrets.TEST_USERNAME }}
            MAESTRO_TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
      - uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 33
          env: |
            MAESTRO_TEST_USERNAME=${{ secrets.TEST_USERNAME }}
            MAESTRO_TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
          arch: x86_64
          ram-size: 4192M
          target: google_apis
          emulator-options: -no-window -no-snapshot -screen no-touch -noaudio -memory 2048 -no-boot-anim -gpu auto -camera-back none
          script: ./github_action_install_apk.sh

      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: maestro-report
          path: |
            ./**/.maestro/tests
            /Users/runner/.maestro/tests/
            report.xml