name: Maestro test on emulator

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - uses: dniHze/maestro-test-action@v1
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          ram-size: 2048M
          target: google_apis
          script: maestro test --format=junit --output=report.xml --no-ansi .maestro