name: Build Release App bundle

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: actions/checkout@v3
      - name: set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build prod
        run: ./gradlew openmrs-client:bundleRelease
        env:
          KEYSTORE_FILE: ${{ steps.decode_keystore.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_ALIAS_NAME: ${{ secrets.KEYSTORE_ALIAS_NAME }}
          KEYSTORE_ALIAS_PASS: ${{ secrets.KEYSTORE_ALIAS_PASS }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: BlopUp Client Bundle
          path: openmrs-client/build/outputs/bundle/release/openmrs-client-release.aab
      - uses: ncipollo/release-action@v1
        with:
          artifacts: openmrs-client/build/outputs/bundle/release/openmrs-client-release.aab
      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: edu.upc
          releaseFiles: openmrs-client/build/outputs/bundle/release/openmrs-client-release.aab
          track: internal
#          status: inProgress
